# Generated by Django 2.2.2 on 2019-06-30 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_no', models.IntegerField()),
                ('resume', models.FileField(upload_to='resume/', verbose_name='')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Education')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Gender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
