# Generated by Django 2.2.3 on 2019-07-05 10:31

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerdetail',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='job_seeker/', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seekerdetail',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
