# Generated by Django 2.2.3 on 2019-07-23 07:40

from django.db import migrations, models
import home.validator


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_auto_20190705_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerdetail',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True, validators=[home.validator.mobile_no_validation]),
        ),
        migrations.AlterField(
            model_name='seekerdetail',
            name='name',
            field=models.CharField(max_length=100, validators=[home.validator.name_validation]),
        ),
        migrations.AlterField(
            model_name='seekerdetail',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=9),
        ),
    ]
