# Generated by Django 2.2.3 on 2019-07-23 07:47

from django.db import migrations, models
import home.validator


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_auto_20190723_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerdetail',
            name='phone_no',
            field=models.CharField(blank=True, max_length=9, validators=[home.validator.phone_no_validation]),
        ),
    ]
