# Generated by Django 2.2.3 on 2019-07-23 07:52

from django.db import migrations, models
import home.validator


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_auto_20190723_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerdetail',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[home.validator.mobile_no_validation]),
        ),
    ]
