# Generated by Django 2.2.3 on 2019-07-31 02:22

from django.db import migrations, models
import home.validator


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_auto_20190723_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerdetail',
            name='date_of_birth',
            field=models.DateField(validators=[home.validator.date_of_birth_validation]),
        ),
    ]
