# Generated by Django 2.2.3 on 2019-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190630_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
