# Generated by Django 2.2.3 on 2019-08-29 02:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='category/', verbose_name=''),
        ),
    ]
