# Generated by Django 2.2.3 on 2019-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('role', models.CharField(choices=[('company', 'Company'), ('job_seeker', 'Job Seeker')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FaqCompany',
        ),
        migrations.DeleteModel(
            name='FaqSeeker',
        ),
    ]
