# Generated by Django 2.2.3 on 2019-07-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_district_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='province',
            new_name='province_name',
        ),
        migrations.AddField(
            model_name='province',
            name='province_no',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
