# Generated by Django 2.2.3 on 2019-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
