# Generated by Django 2.2.3 on 2019-07-31 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190731_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='province_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='district_wise_province_no', to='home.Province'),
            preserve_default=False,
        ),
    ]
