# Generated by Django 2.2.3 on 2019-08-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_question', models.CharField(max_length=200)),
                ('company_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FaqSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_question', models.CharField(max_length=200)),
                ('seeker_answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
