# Generated by Django 2.2.3 on 2019-07-31 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.validator
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('job_seeker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=9, validators=[home.validator.phone_no_validation])),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, validators=[home.validator.mobile_no_validation])),
                ('company_registration_date', models.DateField(blank=True, null=True, validators=[home.validator.registration_date_validation])),
                ('company_image', sorl.thumbnail.fields.ImageField(upload_to='company/', verbose_name='')),
                ('slug', models.SlugField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail_district', to='home.District')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail_province', to='home.Province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_level', models.CharField(max_length=15)),
                ('vacancy_no', models.IntegerField()),
                ('experience', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
                ('deadline', models.DateField(validators=[home.validator.deadline_validation])),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_category', to='home.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_company', to='company.CompanyDetail')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_education', to='home.Education')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now=True)),
                ('applicant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_resume_applicant_name', to='job_seeker.SeekerDetail')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_resume_job_title', to='company.JobPost')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_job', to='company.JobPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='job_seeker.SeekerDetail')),
            ],
        ),
    ]
