# Generated by Django 2.2.3 on 2019-08-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobtype'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_requirement',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_post_job_type', to='home.JobType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='negotiable',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(blank=True),
        ),
    ]
