# Generated by Django 2.2.3 on 2019-08-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seeker', '0001_initial'),
        ('company', '0001_initial'),
        ('home', '0002_auto_20190803_1622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedresume',
            name='applicant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_resume_applicant_name', to='job_seeker.SeekerDetail'),
        ),
        migrations.AddField(
            model_name='receivedresume',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_resume_job_title', to='company.JobPost'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_category', to='home.Category'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_company', to='company.CompanyDetail'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_education', to='home.Education'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_job_level', to='home.JobLevel'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_job_type', to='home.JobType'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail_district', to='home.District'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail_province', to='home.Province'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
