# Generated by Django 2.2.2 on 2019-06-30 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
        ('job_seeker', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedresume',
            name='applicant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.SeekerDetail'),
        ),
        migrations.AddField(
            model_name='receivedresume',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JobPost'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyDetail'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Education'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
