# Generated by Django 2.2.3 on 2019-07-05 10:31

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190630_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='company_image',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='company/', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetail',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
