# Generated by Django 2.2.3 on 2019-08-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190814_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptracker',
            name='job_ip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='iptracker_job_ip', to='company.JobPost'),
        ),
    ]
