# Generated by Django 2.2.3 on 2019-08-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
        ('company', '0002_auto_20190801_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='CompanyNotification',
        ),
    ]
