# Generated by Django 2.2.3 on 2019-08-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
        ('company', '0003_auto_20190801_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyNotification',
            new_name='Notification',
        ),
    ]
