# Generated by Django 2.2.3 on 2019-07-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190705_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedresume',
            name='applied_date',
            field=models.DateField(auto_now=True),
        ),
    ]
