# Generated by Django 2.2.3 on 2019-08-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190814_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptracker',
            name='job_ip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='iptracker_job_ip', to='company.JobPost'),
            preserve_default=False,
        ),
    ]
