# Generated by Django 2.2.3 on 2019-07-23 09:20

from django.db import migrations, models
import home.validator


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_receivedresume_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='company_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[home.validator.mobile_no_validation]),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='phone_no',
            field=models.CharField(blank=True, max_length=9, validators=[home.validator.phone_no_validation]),
        ),
    ]
