# Generated by Django 2.2.3 on 2019-08-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190814_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptracker',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
