# Generated by Django 2.2.3 on 2019-08-01 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190801_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_job_level', to='home.JobLevel'),
        ),
    ]
