# Generated by Django 2.2.3 on 2019-07-31 02:22

from django.db import migrations, models
import django.db.models.deletion
import home.validator


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_auto_20190731_0807'),
        ('company', '0005_auto_20190723_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='company_registration_date',
            field=models.DateField(blank=True, null=True, validators=[home.validator.registration_date_validation]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateField(validators=[home.validator.deadline_validation]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JobPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.SeekerDetail')),
            ],
        ),
    ]
