# Generated by Django 2.2.3 on 2019-07-31 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190731_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_category', to='home.Category'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_company', to='company.CompanyDetail'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_education', to='home.Education'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_job', to='company.JobPost'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='job_seeker.SeekerDetail'),
        ),
        migrations.AlterField(
            model_name='receivedresume',
            name='applicant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_resume_applicant_name', to='job_seeker.SeekerDetail'),
        ),
        migrations.AlterField(
            model_name='receivedresume',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_resume_job_title', to='company.JobPost'),
        ),
    ]
