# Generated by Django 2.2.3 on 2019-08-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190801_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='company_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
